const defaults={sheetW:69,sheetH:89,grip:1,left:.5,right:.5,top:.5,bottom:.5,gapX:.3,gapY:.3,waste:5,designs:[{name:'Etiqueta A',w:10,h:12,qty:1000,color:'#8ec5e8'},{name:'Etiqueta B',w:5,h:8,qty:2000,color:'#a8d49e'}]};
const sheetFields=[['sheetW','Ancho del pliego','cm',1],['sheetH','Alto del pliego','cm',1],['gapX','Separación horizontal','cm',.1],['gapY','Separación vertical','cm',.1],['grip','Pinza','cm',.1],['left','Margen izquierdo','cm',.1],['right','Margen derecho','cm',.1],['top','Margen superior','cm',.1],['bottom','Margen inferior','cm',.1],['waste','Merma','%',.5]],palette=['#8ec5e8','#a8d49e','#f6c56f','#e9a3b4','#baa6e8','#83d7ce'];
let values=structuredClone(defaults);try{values={...values,...JSON.parse(localStorage.getItem('calculadora-pliegos-multiple')||'{}')}}catch{}
const fieldRoot=document.getElementById('fields'),designRoot=document.getElementById('designs');
sheetFields.forEach(([key,label,unit,step])=>{const wrap=document.createElement('label');wrap.innerHTML=`<span>${label}</span><div class="inputWrap"><input inputmode="decimal" type="number" min="0" step="${step}" value="${values[key]}"><b>${unit}</b></div>`;wrap.querySelector('input').addEventListener('input',e=>{values[key]=Math.max(0,Number(e.target.value)||0);save(false)});fieldRoot.append(wrap)});
function save(rebuild=true){localStorage.setItem('calculadora-pliegos-multiple',JSON.stringify(values));if(rebuild)renderDesigns();render()}
function renderDesigns(){designRoot.innerHTML='';values.designs.forEach((d,i)=>{const card=document.createElement('div');card.className='designCard';card.style.setProperty('--design-color',d.color);card.innerHTML=`<div class="designTop"><input class="name" value="${d.name}"><button class="remove" type="button">Eliminar</button></div><div class="designFields"><label><span>Ancho</span><div class="inputWrap"><input data-k="w" inputmode="decimal" type="number" min="0" step="0.1" value="${d.w}"><b>cm</b></div></label><label><span>Alto</span><div class="inputWrap"><input data-k="h" inputmode="decimal" type="number" min="0" step="0.1" value="${d.h}"><b>cm</b></div></label><label><span>Cantidad</span><div class="inputWrap"><input data-k="qty" inputmode="numeric" type="number" min="0" step="1" value="${d.qty}"><b>unid.</b></div></label></div>`;card.querySelector('.name').addEventListener('input',e=>{d.name=e.target.value;save(false)});card.querySelectorAll('[data-k]').forEach(el=>el.addEventListener('input',e=>{d[e.target.dataset.k]=Math.max(0,Number(e.target.value)||0);save(false)}));card.querySelector('.remove').addEventListener('click',()=>{if(values.designs.length>1){values.designs.splice(i,1);save()}});designRoot.append(card)})}
document.getElementById('addDesign').addEventListener('click',()=>{const i=values.designs.length;values.designs.push({name:`Etiqueta ${String.fromCharCode(65+i)}`,w:5,h:5,qty:1000,color:palette[i%palette.length]});save()});
function pack(){const usableW=Math.max(0,values.sheetW-values.left-values.right),usableH=Math.max(0,values.sheetH-values.grip-values.top-values.bottom),gx=values.gapX,gy=values.gapY,area=usableW*usableH,active=values.designs.map((d,i)=>({...d,i})).filter(d=>d.w>0&&d.h>0&&d.qty>0);
function run(seedOrder){let free=[{x:0,y:0,w:usableW,h:usableH}],placed=[],counts=values.designs.map(()=>0),guard=0;
const contained=(a,b)=>a.x>=b.x-.001&&a.y>=b.y-.001&&a.x+a.w<=b.x+b.w+.001&&a.y+a.h<=b.y+b.h+.001;
function prune(){free=free.filter(r=>r.w>.01&&r.h>.01);free=free.filter((r,i)=>!free.some((q,j)=>i!==j&&contained(r,q)))}
function choose(onlyDi=null){let best=null;for(const d of active){if(onlyDi!==null&&d.i!==onlyDi)continue;for(const f of free){for(const rot of [false,true]){const rw=(rot?d.h:d.w)+gx,rh=(rot?d.w:d.h)+gy;if(rw<=f.w+.001&&rh<=f.h+.001){const areaFit=f.w*f.h-rw*rh,short=Math.min(f.w-rw,f.h-rh),progress=counts[d.i]/Math.max(1,d.qty);const score=areaFit+short*.01+progress*.001;if(!best||score<best.score)best={di:d.i,x:f.x,y:f.y,rw,rh,rot,score}}}}}return best}
function place(c){if(!c)return false;const d=values.designs[c.di],next=[];for(const f of free){const noOverlap=c.x>=f.x+f.w||c.x+c.rw<=f.x||c.y>=f.y+f.h||c.y+c.rh<=f.y;if(noOverlap){next.push(f);continue}if(c.x>f.x)next.push({x:f.x,y:f.y,w:c.x-f.x,h:f.h});if(c.x+c.rw<f.x+f.w)next.push({x:c.x+c.rw,y:f.y,w:f.x+f.w-c.x-c.rw,h:f.h});if(c.y>f.y)next.push({x:f.x,y:f.y,w:f.w,h:c.y-f.y});if(c.y+c.rh<f.y+f.h)next.push({x:f.x,y:c.y+c.rh,w:f.w,h:f.y+f.h-c.y-c.rh})}free=next;prune();placed.push({di:c.di,x:c.x,y:c.y,w:c.rot?d.h:d.w,h:c.rot?d.w:d.h,rot:c.rot});counts[c.di]++;return true}
for(const di of seedOrder)place(choose(di));while(guard++<1500){const c=choose();if(!place(c))break}const used=placed.reduce((s,p)=>s+p.w*p.h,0),valid=active.every(d=>counts[d.i]>0);return{usableW,usableH,placed,counts,efficiency:area?used/area*100:0,valid}}
const original=active.map(d=>d.i),large=[...active].sort((a,b)=>b.w*b.h-a.w*a.h).map(d=>d.i),small=[...large].reverse(),orders=[original,[...original].reverse(),large,small];const options=orders.map(run),valid=options.filter(o=>o.valid);return(valid.length?valid:options).sort((a,b)=>b.efficiency-a.efficiency||b.placed.length-a.placed.length)[0]||{usableW,usableH,placed:[],counts:values.designs.map(()=>0),efficiency:0,valid:false}}
function node(name,attrs,text){const el=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(text!=null)el.textContent=text;return el}
function render(){const r=pack(),valid=r.counts.every((c,i)=>!values.designs[i].qty||c>0);let netSheets=0,wasteSheets=0;r.counts.forEach((c,i)=>{if(c){netSheets=Math.max(netSheets,Math.ceil(values.designs[i].qty/c));if(values.waste<100)wasteSheets=Math.max(wasteSheets,Math.ceil(values.designs[i].qty/(1-values.waste/100)/c))}});if(!valid||values.waste>=100){netSheets=0;wasteSheets=0}document.getElementById('total').textContent=r.placed.length;document.getElementById('net').textContent=netSheets;document.getElementById('wasteSheets').textContent=wasteSheets;document.getElementById('arrangement').textContent=`${values.designs.length} tamaños combinados`;document.getElementById('usable').textContent=`${r.usableW.toFixed(1)} × ${r.usableH.toFixed(1)} cm`;document.getElementById('efficiency').textContent=`${r.efficiency.toFixed(1)}%`;
const breakdown=document.getElementById('breakdown');breakdown.innerHTML='';values.designs.forEach((d,i)=>{const row=document.createElement('div');row.className='breakRow';row.innerHTML=`<span><i class="dot" style="--dot:${d.color}"></i>${d.name} (${d.w} × ${d.h} cm)</span><b>${r.counts[i]} por pliego</b>`;breakdown.append(row)});if(!valid){const row=document.createElement('div');row.className='breakRow';row.innerHTML='<span style="color:#a12626">Una etiqueta no cabe en el área útil.</span>';breakdown.append(row)}
const svg=document.getElementById('sheetDrawing'),scale=8,pad=24,w=Math.max(1,values.sheetW*scale),h=Math.max(1,values.sheetH*scale),ux=pad+values.left*scale,uy=pad+(values.grip+values.top)*scale;svg.innerHTML='';svg.setAttribute('viewBox',`0 0 ${w+pad*2} ${h+pad*2}`);svg.append(node('rect',{class:'sheet',x:pad,y:pad,width:w,height:h,rx:5}),node('rect',{class:'grip',x:pad,y:pad,width:w,height:values.grip*scale}),node('text',{class:'gripText',x:pad+w/2,y:pad+Math.max(9,values.grip*scale/2)},`PINZA ${values.grip} cm`),node('rect',{class:'usable',x:ux,y:uy,width:r.usableW*scale,height:r.usableH*scale}));const seen=values.designs.map(()=>0);r.placed.forEach(p=>{const d=values.designs[p.di],x=ux+p.x*scale,y=uy+p.y*scale;seen[p.di]++;svg.append(node('rect',{class:'piece',x,y,width:p.w*scale,height:p.h*scale,rx:2,fill:d.color,stroke:d.color}),node('text',{class:'pieceNo',x:x+p.w*scale/2,y:y+p.h*scale/2},`${p.di+1}.${seen[p.di]}`))})}
document.getElementById('reset').addEventListener('click',()=>{values=structuredClone(defaults);localStorage.removeItem('calculadora-pliegos-multiple');document.querySelectorAll('#fields input').forEach((el,i)=>el.value=values[sheetFields[i][0]]);save()});renderDesigns();render();
