const defaults={sheetW:69,sheetH:89,grip:1,left:.5,right:.5,top:.5,bottom:.5,designW:10,designH:12,gapX:.3,gapY:.3,quantity:1000,waste:5};
const fields=[['sheetW','Ancho del pliego','cm',1],['sheetH','Alto del pliego','cm',1],['designW','Ancho del diseño','cm',1],['designH','Alto del diseño','cm',1],['gapX','Separación horizontal','cm',.1],['gapY','Separación vertical','cm',.1],['grip','Pinza','cm',.1],['left','Margen izquierdo','cm',.1],['right','Margen derecho','cm',.1],['top','Margen superior','cm',.1],['bottom','Margen inferior','cm',.1],['quantity','Cantidad solicitada','unid.',1],['waste','Merma','%',.5]];
let values={...defaults};try{values={...values,...JSON.parse(localStorage.getItem('calculadora-pliegos')||'{}')}}catch{}
const fieldRoot=document.getElementById('fields');fields.forEach(([key,label,unit,step])=>{const wrap=document.createElement('label');wrap.innerHTML=`<span>${label}</span><div class="inputWrap"><input inputmode="decimal" type="number" min="0" step="${step}" value="${values[key]}"><b>${unit}</b></div>`;wrap.querySelector('input').addEventListener('input',e=>{values[key]=Math.max(0,Number(e.target.value)||0);localStorage.setItem('calculadora-pliegos',JSON.stringify(values));render()});fieldRoot.append(wrap)});
const fit=(span,piece,gap)=>span>0&&piece>0?Math.max(0,Math.floor((span+gap)/(piece+gap))):0;
function calculate(v){const usableW=Math.max(0,v.sheetW-v.left-v.right),usableH=Math.max(0,v.sheetH-v.grip-v.top-v.bottom),normalCols=fit(usableW,v.designW,v.gapX),rotatedCols=fit(usableW,v.designH,v.gapX);let best={normalRows:0,rotatedRows:0,total:0};for(let n=0;n<=fit(usableH,v.designH,v.gapY);n++){const used=n?n*v.designH+(n-1)*v.gapY:0,remaining=Math.max(0,usableH-used-(n?v.gapY:0)),r=fit(remaining,v.designW,v.gapY),total=n*normalCols+r*rotatedCols;if(total>best.total)best={normalRows:n,rotatedRows:r,total}}const target=v.waste>=100?0:Math.ceil(v.quantity/(1-v.waste/100));return{usableW,usableH,normalCols,rotatedCols,target,sheetsNet:best.total?Math.ceil(v.quantity/best.total):0,sheetsWaste:best.total?Math.ceil(target/best.total):0,...best}}
function node(name,attrs,text){const el=document.createElementNS('http://www.w3.org/2000/svg',name);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(text!=null)el.textContent=text;return el}
function render(){const r=calculate(values);total.textContent=r.total;net.textContent=r.sheetsNet;wasteSheets.textContent=r.sheetsWaste;arrangement.textContent=`${r.normalRows} filas normales + ${r.rotatedRows} filas giradas`;usable.textContent=`${r.usableW.toFixed(1)} × ${r.usableH.toFixed(1)} cm`;target.textContent=`${r.target.toLocaleString('es-PE')} unidades`;const svg=document.getElementById('sheetDrawing'),scale=8,pad=24,w=Math.max(1,values.sheetW*scale),h=Math.max(1,values.sheetH*scale),ux=pad+values.left*scale,uy=pad+(values.grip+values.top)*scale;svg.innerHTML='';svg.setAttribute('viewBox',`0 0 ${w+pad*2} ${h+pad*2}`);svg.append(node('rect',{class:'sheet',x:pad,y:pad,width:w,height:h,rx:5}),node('rect',{class:'grip',x:pad,y:pad,width:w,height:values.grip*scale}),node('text',{class:'gripText',x:pad+w/2,y:pad+Math.max(9,values.grip*scale/2)},`PINZA ${values.grip} cm`),node('rect',{class:'usable',x:ux,y:uy,width:r.usableW*scale,height:r.usableH*scale}));let num=1,currentY=uy;function rows(count,cols,pw,ph,rotated){for(let row=0;row<count;row++){const rowWidth=cols?cols*pw+(cols-1)*values.gapX:0,startX=ux+Math.max(0,(r.usableW-rowWidth)*scale/2);for(let col=0;col<cols;col++){const x=startX+col*(pw+values.gapX)*scale,y=currentY;svg.append(node('rect',{class:rotated?'piece rotated':'piece',x,y,width:pw*scale,height:ph*scale,rx:3}),node('text',{class:'pieceNo',x:x+pw*scale/2,y:y+ph*scale/2},num++))}currentY+=(ph+values.gapY)*scale}}rows(r.normalRows,r.normalCols,values.designW,values.designH,false);rows(r.rotatedRows,r.rotatedCols,values.designH,values.designW,true)}
document.getElementById('reset').addEventListener('click',()=>{values={...defaults};localStorage.removeItem('calculadora-pliegos');document.querySelectorAll('input').forEach((el,i)=>el.value=values[fields[i][0]]);render()});render();
